/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConvertersRouteImport } from './routes/converters'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as KenyaToolsRouteImport } from './routes/kenya-tools'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProductivityRouteImport } from './routes/productivity'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsAcreHectareConverterRouteImport } from './routes/tools.acre-hectare-converter'
import { Route as ToolsAgeCalculatorRouteImport } from './routes/tools.age-calculator'
import { Route as ToolsLoanCalculatorRouteImport } from './routes/tools.loan-calculator'
import { Route as ToolsPayeCalculatorRouteImport } from './routes/tools.paye-calculator'
import { Route as ToolsPercentageCalculatorRouteImport } from './routes/tools.percentage-calculator'
import { Route as ToolsSalaryCalculatorRouteImport } from './routes/tools.salary-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertersRoute = ConvertersRouteImport.update({
  id: '/converters',
  path: '/converters',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const KenyaToolsRoute = KenyaToolsRouteImport.update({
  id: '/kenya-tools',
  path: '/kenya-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductivityRoute = ProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAcreHectareConverterRoute =
  ToolsAcreHectareConverterRouteImport.update({
    id: '/tools/acre-hectare-converter',
    path: '/tools/acre-hectare-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsAgeCalculatorRoute = ToolsAgeCalculatorRouteImport.update({
  id: '/tools/age-calculator',
  path: '/tools/age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoanCalculatorRoute = ToolsLoanCalculatorRouteImport.update({
  id: '/tools/loan-calculator',
  path: '/tools/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPayeCalculatorRoute = ToolsPayeCalculatorRouteImport.update({
  id: '/tools/paye-calculator',
  path: '/tools/paye-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPercentageCalculatorRoute =
  ToolsPercentageCalculatorRouteImport.update({
    id: '/tools/percentage-calculator',
    path: '/tools/percentage-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSalaryCalculatorRoute = ToolsSalaryCalculatorRouteImport.update({
  id: '/tools/salary-calculator',
  path: '/tools/salary-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/converters': typeof ConvertersRoute
  '/disclaimer': typeof DisclaimerRoute
  '/kenya-tools': typeof KenyaToolsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/productivity': typeof ProductivityRoute
  '/terms': typeof TermsRoute
  '/tools/acre-hectare-converter': typeof ToolsAcreHectareConverterRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/loan-calculator': typeof ToolsLoanCalculatorRoute
  '/tools/paye-calculator': typeof ToolsPayeCalculatorRoute
  '/tools/percentage-calculator': typeof ToolsPercentageCalculatorRoute
  '/tools/salary-calculator': typeof ToolsSalaryCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/converters': typeof ConvertersRoute
  '/disclaimer': typeof DisclaimerRoute
  '/kenya-tools': typeof KenyaToolsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/productivity': typeof ProductivityRoute
  '/terms': typeof TermsRoute
  '/tools/acre-hectare-converter': typeof ToolsAcreHectareConverterRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/loan-calculator': typeof ToolsLoanCalculatorRoute
  '/tools/paye-calculator': typeof ToolsPayeCalculatorRoute
  '/tools/percentage-calculator': typeof ToolsPercentageCalculatorRoute
  '/tools/salary-calculator': typeof ToolsSalaryCalculatorRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/converters': typeof ConvertersRoute
  '/disclaimer': typeof DisclaimerRoute
  '/kenya-tools': typeof KenyaToolsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/productivity': typeof ProductivityRoute
  '/terms': typeof TermsRoute
  '/tools/acre-hectare-converter': typeof ToolsAcreHectareConverterRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/loan-calculator': typeof ToolsLoanCalculatorRoute
  '/tools/paye-calculator': typeof ToolsPayeCalculatorRoute
  '/tools/percentage-calculator': typeof ToolsPercentageCalculatorRoute
  '/tools/salary-calculator': typeof ToolsSalaryCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/converters'
    | '/disclaimer'
    | '/kenya-tools'
    | '/privacy-policy'
    | '/productivity'
    | '/terms'
    | '/tools/acre-hectare-converter'
    | '/tools/age-calculator'
    | '/tools/loan-calculator'
    | '/tools/paye-calculator'
    | '/tools/percentage-calculator'
    | '/tools/salary-calculator'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/converters'
    | '/disclaimer'
    | '/kenya-tools'
    | '/privacy-policy'
    | '/productivity'
    | '/terms'
    | '/tools/acre-hectare-converter'
    | '/tools/age-calculator'
    | '/tools/loan-calculator'
    | '/tools/paye-calculator'
    | '/tools/percentage-calculator'
    | '/tools/salary-calculator'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/converters'
    | '/disclaimer'
    | '/kenya-tools'
    | '/privacy-policy'
    | '/productivity'
    | '/terms'
    | '/tools/acre-hectare-converter'
    | '/tools/age-calculator'
    | '/tools/loan-calculator'
    | '/tools/paye-calculator'
    | '/tools/percentage-calculator'
    | '/tools/salary-calculator'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ContactRoute: typeof ContactRoute
  ConvertersRoute: typeof ConvertersRoute
  DisclaimerRoute: typeof DisclaimerRoute
  KenyaToolsRoute: typeof KenyaToolsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductivityRoute: typeof ProductivityRoute
  TermsRoute: typeof TermsRoute
  ToolsAcreHectareConverterRoute: typeof ToolsAcreHectareConverterRoute
  ToolsAgeCalculatorRoute: typeof ToolsAgeCalculatorRoute
  ToolsLoanCalculatorRoute: typeof ToolsLoanCalculatorRoute
  ToolsPayeCalculatorRoute: typeof ToolsPayeCalculatorRoute
  ToolsPercentageCalculatorRoute: typeof ToolsPercentageCalculatorRoute
  ToolsSalaryCalculatorRoute: typeof ToolsSalaryCalculatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters': {
      id: '/converters'
      path: '/converters'
      fullPath: '/converters'
      preLoaderRoute: typeof ConvertersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenya-tools': {
      id: '/kenya-tools'
      path: '/kenya-tools'
      fullPath: '/kenya-tools'
      preLoaderRoute: typeof KenyaToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/acre-hectare-converter': {
      id: '/tools/acre-hectare-converter'
      path: '/tools/acre-hectare-converter'
      fullPath: '/tools/acre-hectare-converter'
      preLoaderRoute: typeof ToolsAcreHectareConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/age-calculator': {
      id: '/tools/age-calculator'
      path: '/tools/age-calculator'
      fullPath: '/tools/age-calculator'
      preLoaderRoute: typeof ToolsAgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/loan-calculator': {
      id: '/tools/loan-calculator'
      path: '/tools/loan-calculator'
      fullPath: '/tools/loan-calculator'
      preLoaderRoute: typeof ToolsLoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/paye-calculator': {
      id: '/tools/paye-calculator'
      path: '/tools/paye-calculator'
      fullPath: '/tools/paye-calculator'
      preLoaderRoute: typeof ToolsPayeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/percentage-calculator': {
      id: '/tools/percentage-calculator'
      path: '/tools/percentage-calculator'
      fullPath: '/tools/percentage-calculator'
      preLoaderRoute: typeof ToolsPercentageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/salary-calculator': {
      id: '/tools/salary-calculator'
      path: '/tools/salary-calculator'
      fullPath: '/tools/salary-calculator'
      preLoaderRoute: typeof ToolsSalaryCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorsRoute: CalculatorsRoute,
  ContactRoute: ContactRoute,
  ConvertersRoute: ConvertersRoute,
  DisclaimerRoute: DisclaimerRoute,
  KenyaToolsRoute: KenyaToolsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductivityRoute: ProductivityRoute,
  TermsRoute: TermsRoute,
  ToolsAcreHectareConverterRoute: ToolsAcreHectareConverterRoute,
  ToolsAgeCalculatorRoute: ToolsAgeCalculatorRoute,
  ToolsLoanCalculatorRoute: ToolsLoanCalculatorRoute,
  ToolsPayeCalculatorRoute: ToolsPayeCalculatorRoute,
  ToolsPercentageCalculatorRoute: ToolsPercentageCalculatorRoute,
  ToolsSalaryCalculatorRoute: ToolsSalaryCalculatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
